main = "./src/index.ts"
name = "website-helper-worker"
compatibility_date = "2022-07-26"

routes = [{ pattern = "utils.the-guild.dev", custom_domain = true }]

send_email = [{ type = "send_email", name = "EMAIL_SENDER" }]
